shell = "fish"
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
#decorations = 'None'
opacity = 0.7
blur = true
startup_mode = "Maximized"

[font]
normal = {family = "FantasqueSansM Nerd Font", style="Regular"}
# builtin_box_drawing = false
